---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: instance
    image: ${MOLECULE_IMAGE}
    pre_build_image: true
    command: /lib/systemd/systemd
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw

provisioner:
  name: ansible
  inventory:
    host_vars:
      instance:
        nvidia_container_host_manage_repository: false
        nvidia_container_host_packages: []
        nvidia_container_host_prerequisite_packages: []
        nvidia_container_host_configure_runtime: false
        nvidia_container_host_manage_grub_cmdline_linux_default: false
        nvidia_container_host_reboot_after_grub_update: false

scenario:
  name: default

test_sequence:
  - destroy
  - create
  - converge
  - idempotence
  - destroy
